sudo: required

language: cpp

compiler:
  - clang
  - gcc-4.8
  - gcc
  - gcc-6

env:
  - TARGET=doc
  - TARGET=python
  - TARGET=java
  - TARGET=node4
  - TARGET=node5
  - TARGET=node6

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - if [ "$CC" == "gcc-4.8" ]; then export CC=gcc-4.8; fi
  - if [ "$CXX" == "g++-4.8" ]; then export CXX=g++-4.8; fi
  - if [ "$CC" == "gcc-6" ]; then export CC=gcc-6; fi
  - if [ "$CXX" == "g++-6" ]; then export CXX=g++-6; fi
  - if [ "$CC" == "clang" ]; then export CC=clang-3.8; fi
  - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.8; fi
  - docker-compose build ${TARGET}

script:
  - docker-compose run ${TARGET}
